# Generated by Django 3.2.5 on 2021-09-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ingredient Name')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity of Ingredients')),
                ('unit', models.CharField(max_length=20, verbose_name='Ingredient Unit Measurement')),
                ('price', models.DecimalField(decimal_places='2', default=0.0, max_digits=4, verbose_name='Price Per Unit of Ingredient')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dish Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Price for Dish')),
            ],
            options={
                'verbose_name_plural': 'Menu Dishes',
            },
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity of Ingredient Required')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingredient', verbose_name='Dish Ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem', verbose_name='Dish Name')),
            ],
            options={
                'verbose_name_plural': 'Recipe Requirements',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Purchase Recorded')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem', verbose_name='Dish Name')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
